### ISSUE TITLE
iTerm 2 Script hang if a hotkey window exists

### ISSUE THREAD

**Issue by atika** [Hejki/ssh-connector#1]
I don't know if this is a problem with my configuration or a bug of iTerm 2, but I had the same problem in my script to open a window with the current Finder path.
When a **hotkey window exists**, calling `"current window"` crash the applescript script. I found a workaround and tested it with the Hotkey window open, dismissed or closed, and it seems to work as expected.

```applescript
tell application id "com.googlecode.iterm2"
	set c to " %@"
	
	try
		# Try to get current window of iTerm
		set myterm to current window
		
		tell current session of myterm
			if is processing then
				# Execute command
				write text c
			else
				# Create a new tab and execute command
				tell myterm to create tab with default profile command c
			end if
		end tell
	on error
		# Create a new window and execute command
		create window with default profile command c
	end try
	
	activate
end tell
```

**Comment by Hejki** [comment]
Script for iTerm updated as you suggested. I test it and works for all my combinations. I release it soon. Thanks.
